### ISSUE TITLE
Utility classes

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#12]
- [x] Text-align left, center, right, justify
- [x] Float left, right 
- [x] Un-bullets lists
- [x] Font weight light, normal, bold
- [x] Add more classes here

**Comment by zeokav** [comment]
I'd like to take this up.

**Comment by ummahusla** [comment]
@zeokav Feel free to. Hopefully I will finish with grid when I get home.

**Comment by zeokav** [comment]
Is there a naming convention you're following for the classes?

**Comment by ummahusla** [comment]
At the moment, no really but I thought about: 

`column` as `potato`
`columns` as `potatoes`
`row`, `container` as `row` and `container`

**Comment by zeokav** [comment]
And just confirming before I start... You require CSS classes for the attributes in the checklist, right? 🤔

**Comment by ummahusla** [comment]
Yeah, so `.text-center` would be a `.text-center { text-align: center }` :blush:

If you about any other helper/utility classes, please add them. I can always refactor them later on.

**Comment by zeokav** [comment]
I have sent a pull request against this issue. Please review it and let me know if anything else is required!

**Comment by ummahusla** [comment]
@zeokav Will do soon

**Comment by ummahusla** [comment]
@zeokav Merged, thank you for the help.
