### ISSUE TITLE
Create contribution guide

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#2]
- [x] Create `contribute.md`.
- [x] Add a basic explanation how to contribute to this repository using `hotfix` or `feature` branches.
- [x] Add links to [**issues**](https://github.com/PotatoCSS/PotatoCSS/issues).

**Comment by zeokav** [comment]
What all needs to be specified in the contribution guide?

**Comment by ummahusla** [comment]
@zeokav You can start with creating a `contribution.md` and migrating current information into it. Might be worth to explain when you need to create `hotfix/IE_bug` and `feature/mobile_grid` branches. In the end, worth to add links to repository issues.

**Comment by ummahusla** [comment]
Done, PR #10
