### ISSUE TITLE
Create button classes

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#21]
- [ ] Buttons sizing
- [ ] Buttons colors

**Comment by zeokav** [comment]
Hi, how many sizes and colours do you require @ummahusla ?

**Comment by ummahusla** [comment]
@zeokav It's a good question, I'll have a think about that.

**Comment by zeokav** [comment]
I'm adding quite a few. Will send a PR in a bit. 😄

**Comment by ummahusla** [comment]
@zeokav I'm doing it as well atm :metal:
