### ISSUE TITLE
Add code examples

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#31]
Use **PotatoCSS** framework to create a several examples pages as an example.

**Comment by Crocmagnon** [comment]
Do you have any particular requirement ?
I created a basic sample page (see #36) using the classes provided in your CSS but maybe you expect something more elaborated ?

**Comment by ummahusla** [comment]
@Crocmagnon I've just checked your PR. This is okay for documentation, but the thing is that I already made this file, in order to test the framework on my local machine. Personally, I would like to see several examples of landing pages.

**Comment by Crocmagnon** [comment]
Hm okay, I understand. Like "real world" example pages ? 🤔
Could you be just a little bit more specific ? 😊

**Comment by ummahusla** [comment]
@Crocmagnon One-page statics html/css template would be nice. Should clean and minimal. You can find [**inspiration here**](https://psdrepo.com/tag/free-psd-website-templates/).
