### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#34]
:beetle: Make a framework testing in order to find out all the cross-browser bugs.

**Comment by alangaurav** [comment]
You could use Browser Sandbox, it's only for window. The only draw back is you can only test on the latest version of each browser. https://turbo.net/browsers. This might be a quick solution for you.

**Comment by ummahusla** [comment]
@catatonia Yeah, I've heard about it, thanks. I think that the main thing will be to test the older browser support like IE8-10 and so on.
