### ISSUE TITLE
Features to implement before launch

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#7]
- [x] Global
- [x] Grid
- [x] Utilities
- [x] Typography
- [x] Forms
- [x] Buttons

**Comment by ZCoderGuy** [comment]
I might just be thick skulled but what do you want done here?

**Comment by ummahusla** [comment]
@ZCoderGuy Thank you for a reply. Issue title sound really confusing. Initially, this is the list of features I'm going to implement to this framework.
