### ISSUE TITLE
Create modal class

### ISSUE THREAD

**Issue by ummahusla** [ummahusla/PotatoCSS#78]

**Comment by bobharley** [comment]
I would like to help on this.

**Comment by ummahusla** [comment]
@bobharley Cool. 

* You will need to create a `/js/script.js` and put your all js logic there.
* All styles go to same `/styles` folder.
* Ignore `SASS/LESS` for now.

**Comment by bobharley** [comment]
Okay, I'll start working on it.
I will be using [bootstrap 4 modal](https://v4-alpha.getbootstrap.com/components/modal/) as a reference.

**Comment by ummahusla** [comment]
@bobharley Sounds good for me

**Comment by bobharley** [comment]
It's done. Check the PR.

**Comment by bobharley** [comment]
@ummahusla I think you should add a build system, like gulp, for easy development. I had to setup my own.

**Comment by ummahusla** [comment]
@bobharley Thank you for the contribution. I've created a [task for `gulp`](https://github.com/ummahusla/PotatoCSS/issues/108). Might be a cool idea you could help with the gulp build first. Then, we can merge your PR for modal and you can carry on with tooltip. How do you feel about it?

**Comment by bobharley** [comment]
@ummahusla yeah, I'll make another branch from master.
